# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 317bf3cd15eecc769247d41eaff7454963bccb9e00fe5f0a63c6a20250e5bfa33d403248294a7300cc8481ec3041d664f31752da339bb6f7c3bb9488fe1a75ad

test:
  secret_key_base: 46c1425d7ba441649aab6f509e32c9ccfeeae8e1b04bd27d3051f3d8b3cfe45df24ba43a4e598e7b01c47a0645f4cb7fb6cbc2fa04f72defaaef460fa3a47584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
